name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --audit false
      - name: Run linter
        run: npm run lint
      - name: Create docker images
        run: |
          docker build -t ghcr.io/fabulator/export-map-as-image:latest .
          docker push ghcr.io/fabulator/export-map-as-image:latest
